#! /bin/sh

### BEGIN INIT INFO
# Provides:          rfled-server
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Provides a small python server for smart LED control
# Description: Provides a small python server for smart LED control
### END INIT INFO

N=/etc/init.d/rfled-server
RFLED_PATH=/usr/local/bin

set -e

case "$1" in
  start)
	# make sure privileges don't persist across reboots
	/usr/bin/python3 ${RFLED_PATH}/led.py &
	/usr/bin/python3 ${RFLED_PATH}/admin.py &
	;;
  stop|reload|restart|force-reload|status)
	
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
