#! /bin/sh

### BEGIN INIT INFO
# Provides:		rfled-server
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	RFLED-Server for Milight LEDs
### END INIT INFO

set -e

# /etc/init.d/rfled-server: start and stop the rfled-server service

test -x /usr/sbin/rfled-server || exit 0
( /usr/sbin/rfled-server -h 2>&1 | grep -q Usage ) 2>/dev/null || exit 0

umask 022

if test -f /etc/default/rfled-server; then
    . /etc/default/rfled-server
fi

. /lib/lsb/init-functions

if [ -n "$2" ]; then
    RFLED_OPTS="$RFLED_OPTS $2"
fi

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_for_upstart() {
    if init_is_upstart; then
	exit $1
    fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	check_for_upstart 1
	log_daemon_msg "Starting rfled-server" "rfled-server" || true
	if start-stop-daemon --start --quiet --oknodo --background --pidfile /var/run/rfled-server.pid --make-pidfile --exec /usr/sbin/rfled-server -- $RFLED_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	check_for_upstart 0
	log_daemon_msg "Stopping rfled-server" "rfled-server" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/rfled-server.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	check_for_upstart 1
	log_daemon_msg "Restarting rfled-server" "rfled-server" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/rfled-server.pid
	check_dev_null log_end_msg
	if start-stop-daemon --start --quiet --oknodo --background --pidfile /var/run/rfled-server.pid --make-pidfile --exec /usr/sbin/rfled-server -- $RFLED_OPTS; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  try-restart)
	check_for_upstart 1
	log_daemon_msg "Restarting rfled-server" "rfled-server" || true
	RET=0
	start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/rfled-server.pid || RET="$?"
	case $RET in
	    0)
		# old daemon stopped
		check_dev_null log_end_msg
		if start-stop-daemon --start --quiet --oknodo --background --pidfile /var/run/rfled-server.pid --make-pidfile --exec /usr/sbin/rfled-server -- $RFLED_OPTS; then
		    log_end_msg 0 || true
		else
		    log_end_msg 1 || true
		fi
		;;
	    1)
		# daemon not running
		log_progress_msg "(not running)" || true
		log_end_msg 0 || true
		;;
	    *)
		# failed to stop
		log_progress_msg "(failed to stop)" || true
		log_end_msg 1 || true
		;;
	esac
	;;

  status)
	check_for_upstart 1
	status_of_proc -p /var/run/rfled-server.pid /usr/sbin/rfled-server rfled-server && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/rfled-server {start|stop|restart|try-restart|status}" || true
	exit 1
esac

exit 0
